require "Battle/Manager/BattleSceneManager"
require "Battle/Manager/ActorManager"
require "Battle/Manager/SkillManager"
require "Battle/Manager/BuffManager"
require "Battle/Manager/InstanceIdManager"
require "Battle/Manager/EventManager"