require "Battle/BattleScene/init"
require "Battle/Actor/init"
require "Battle/Manager/init"
require "Battle/Skill/init"
require "Battle/Modifier/init"
require "Battle/Effect/init"
require "Battle/Commond/init"